version: "3.8"


services:

  backend:
    container_name: ecommerce_backend
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: ecommerce_db
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testname
    ports:
      - 5432:5432

volumes:
  postgres_data:
