# Generated by Django 4.0.5 on 2023-07-07 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='change_pw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='account_users',
        ),
        migrations.CreateModel(
            name='ShopMember',
            fields=[
                ('cleated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager')], default='manager', max_length=255, verbose_name='Role')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_members', to=settings.AUTH_USER_MODEL, verbose_name='Shop Member')),
            ],
            options={
                'verbose_name': 'Shop Member',
                'verbose_name_plural': 'Shop Members',
                'db_table': 'account_shop_members',
                'ordering': ['user'],
            },
        ),
    ]
